-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/simple_tasks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/simple_tasks (
  st_check_id BLOB NOT NULL, st_user INTEGER UNSIGNED NOT NULL,
  st_duedate BLOB DEFAULT NULL, st_text CLOB NOT NULL,
  st_completed INTEGER NOT NULL
);

CREATE UNIQUE INDEX st_check_id ON /*_*/simple_tasks (st_check_id);
