-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/simple_tasks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/simple_tasks (
  st_check_id VARBINARY(255) NOT NULL,
  st_user INT UNSIGNED NOT NULL,
  st_duedate BINARY(14) DEFAULT NULL,
  st_text LONGTEXT NOT NULL,
  st_completed INT NOT NULL,
  UNIQUE INDEX st_check_id (st_check_id)
) /*$wgDBTableOptions*/;
