-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/simple_tasks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE simple_tasks (
  st_check_id TEXT NOT NULL, st_user INT NOT NULL,
  st_duedate TIMESTAMPTZ DEFAULT NULL,
  st_text TEXT NOT NULL, st_completed INT NOT NULL
);

CREATE UNIQUE INDEX st_check_id ON simple_tasks (st_check_id);
